language: node_js
node_js:
- 12
jobs:
  include:
  - stage: deploy-prod
    script: skip
    deploy:
      skip_cleanup: true
      provider: script
      script: bash .travis/deploy.sh
      on:
        branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_884baa815931_key -iv $encrypted_884baa815931_iv
  -in travis.enc -out .travis/travis -d
